#ifndef __NETLICENSING_VERSION__
#define __NETLICENSING_VERSION__

#define NETLICENSING_VERSION_MAJOR 0
#define NETLICENSING_VERSION_MINOR 0
#define NETLICENSING_VERSION_TINY  1

#define NETLICENSING_VERSION "0.0.1"

// the format of this version is: MMmmtt
// M = Major version, m = minor version, t = tiny version
#define LIBED2K_VERSION_NUM ((NETLICENSING_VERSION_MAJOR * 10000) + (NETLICENSING_VERSION_MINOR * 100) + NETLICENSING_VERSION_TINY)

#endif //__NETLICENSING_VERSION__
